name: FloodgateCommandsViaChat
version: ${project.version}
description: ${project.description}
author: regulad

main: xyz.regulad.floodgatecommandsviachat.FloodgateCommandsViaChat
api-version: 1.17
depend:
  - floodgate
libraries:
  - org.jetbrains:annotations:23.0.0
  - org.bstats:bstats-bukkit:2.2.1
